name: Jekyll Site CI/CD

# 触发条件优化
on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次，减少资源消耗
  push:
    branches: 
      - master  # 修改为 master 分支
      - develop
    paths-ignore:      # 不再忽略 .md 文件
      - 'docs/**'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  TZ: Asia/Shanghai
  JEKYLL_ENV: ${{ github.event.inputs.environment || 'production' }}
  RUBY_VERSION: '3.1'
  NODE_VERSION: '16'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true  # 支持 Git LFS

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      # 优化的缓存策略
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor/bundle
            .jekyll-cache
            _site
            node_modules
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/Gemfile.lock', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: ${{ env.JEKYLL_ENV }}

      - name: Verify and Test Build
        run: |
          if [ ! -d "_site" ]; then
            echo "构建失败 - _site 目录未找到"
            exit 1
          fi
          # 检查关键文件
          for file in index.html 404.html; do
            if [ ! -f "_site/$file" ]; then
              echo "错误：$file 未生成"
              exit 1
            fi
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: site-${{ github.sha }}
          path: ./_site
          retention-days: 7

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master' && env.JEKYLL_ENV == 'production'  # 修改为 master 分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_site
          commit_message: "部署: ${{ github.event.head_commit.message || 'Manual deployment' }}"
          full_commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
