name: Jekyll Site CI/CD

# 触发条件
on:
  schedule:
    # 使用更清晰的注释说明时间
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行（北京时间 08:00）
  push:
    branches: 
      - main
      - develop  # 添加开发分支支持
  # 添加手动触发支持
  workflow_dispatch:

# 环境变量配置
env:
  TZ: Asia/Shanghai
  JEKYLL_ENV: production
  RUBY_VERSION: '3.1'  # 将 Ruby 版本提取为变量

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # 添加并发控制，避免同时运行多个工作流
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 优化克隆深度

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      # 优化缓存配置
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor/bundle
            .jekyll-cache
            _site
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
        
      # 添加构建产物验证
      - name: Verify Build
        run: |
          if [ ! -d "_site" ]; then
            echo "Build failed - _site directory not found"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-${{ github.sha }}  # 添加提交哈希便于追踪
          path: ./_site
          retention-days: 7  # 设置保留时间

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_site
          # 添加部署相关配置
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          full_commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
